# Generated by Django 4.2.1 on 2023-05-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_account'),
        ('polls_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polldetail',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
